[package]
name = "cursivetry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.16"
vrsc-rpc = { path = "../rust-vrsc-rpc/client" }
lazy_static = "1.4"